import { Injectable } from "@nestjs/common";

@Injectable()
export class quotes {
    quotes(){
        const quotes = [
            "I told my wife she was drawing her eyebrows too high. She looked surprised.",
            "I used to play piano by ear, but now I use my hands.",
            "I'm reading a book on the history of glue. I can't put it down!",
            "I told my wife she was shouting, but she didn't hear me.",
            "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
            "I'm reading a book about teleportation. It's bound to take me somewhere.",
            "Why did the tomato turn red? Because it saw the salad dressing!",
            "I'm not arguing, I'm just explaining why I'm right.",
            "Why did the scarecrow win an award? Because he was outstanding in his field.",
            "I used to be indecisive, but now I'm not sure.",
            "Why don't scientists trust atoms? Because they make up everything.",
            "I don't always procrastinate, but when I do, I prefer to do it later.",
            "Why did the bicycle fall over? Because it was two-tired.",
            "I've got a photographic memory, but I always forget to put in the memory card.",
            "Why don't skeletons fight each other? They don't have the guts.",
            "I'm on a whiskey diet. I've lost three days already.",
            "Why don't seagulls fly by the bay? Because then they'd be bagels.",
            "I'm reading a book on anti-gravity. It's impossible to put down!",
            "Why did the cookie go to the doctor? Because it was feeling crumbly.",
            "I'm in shape... round is a shape.",
            "Why don't crabs give to charity? Because they're shellfish.",
            "I'm reading a book on the history of clocks. It's about time!",
            "Why did the banana go to the doctor? Because it wasn't peeling well.",
            "I'm on a seafood diet. I see food and I eat it.",
            "I'm writing a book on the dangers of drinking. I'm not sure if it's going to have a happy ending or not.",
            "Why did the chicken cross the playground? To get to the other slide.",
            "I'm on a diet, but I have cheat days on days that end with 'y'.",
            "Why don't ants get sick? Because they have tiny ant-bodies.",
            "I'm reading a book on helium. It's impossible to put down!",
            "Why did the grape stop in the middle of the road? Because he ran out of juice.",
            "I'm not lazy, I'm just conserving energy.",
            "I'm reading a book on the history of calendars. I can't wait to see how it ends.",
            "Why did the mushroom go to the party? Because he was a fungi.",
            "I'm on a diet, but I still need my chocolate fix. So I eat chocolate-covered diet pills.",
            "I'm writing a book on how to procrastinate. I'll finish it later.",
            "Why don't elephants play cards in the jungle? There are too many cheetahs.",
            "Why did the man put his money in the freezer? He wanted cold hard cash.",
            "I told my wife she was drawing her eyebrows too high.",
            "If time travel is possible, why haven't we met any time travelers from the future yet?",
            "Do insects see the world in slow motion?",
            "If two people switch bodies, which one is actually in the other's body?",
            "If our brains were simple enough for us to understand them, we would be too simple to understand them.",
            "If you could travel to the edge of the universe, what would be on the other side?",
            "What if we're all just characters in someone else's dream?",
            "What if our dreams are just glimpses of alternate realities?",
            "If a tree falls in a forest and no one is around to hear it, does it make a sound?",
            "What if we are all just living in a simulation?",
            "Why do we park in a driveway and drive on a parkway?",
            "If you could see the air around you, what would it look like?",
            "What if the universe is just one of many, each with different physical laws?",
            "What if all the stars in the universe are just the atoms of a giant being?",
            "If you could communicate with animals, what would they say?",
            "What if we're all just brains in jars being fed sensory information?",
            "What if we could see other dimensions, but our brains aren't wired for it?",
            "Why do we say 'heads up' when we want someone to duck?",
            "If you could live forever, what would you do with all that time?",
            "What if every time we make a decision, a parallel universe is created with the opposite outcome?",
            "If aliens exist, why haven't they made contact with us?",
            "What if the universe is just a giant hologram?",
            "Why do we call it a building if it's already built?",
            "If our cells are constantly regenerating, are we really the same person we were 10 years ago?",
            "What if we could travel faster than the speed of light?",
            "Why do we have dreams that we can't remember?",
            "What if we could breathe underwater?",
            "If we could harness the power of the sun, what could we accomplish?",
            "What if we could read other people's thoughts?",
            "If we could travel to other planets, what would we find?",
            "What if we're all just living in a giant ant farm?",
            "Why do we say 'I slept like a baby' when babies wake up every few hours?",
            "What if we could teleport?",
            "If we could communicate with extraterrestrial life, what would we say?",
            "Why do we shake hands as a greeting?",
            "What if we could see into the future?",
            "If time is money, why do we waste so much of it?",
            "What if we could control the weather?",
            "Why do we have a fear of the dark?",
            "If we could live on other planets, would we evolve differently?",
            "What if we could fly without any technological assistance?",
            "If we could communicate with people who have passed away, what would we ask them?",
            "Why do we say 'the early bird gets the worm' when the second mouse gets the cheese?",
            "What if there's no such thing as free will?",
            "If we could harness the power of black holes, what could we accomplish?",
            "Why do we have to sleep?",
            "What if we could create a perfect virtual reality?",
            "If we could see the entire electromagnetic spectrum, what would we discover?",
            "What if we could live without a physical body?",
            "Why do we feel nostalgia for things that we never experienced?",
            "If we could communicate with our pets, what would they tell us?",
            "What if we could understand all languages?",
            "If we could travel through time, would we be able to change the past?",
            "Why do we always want what we can't have?",
            "What if we could communicate with plants?",
            "If we could experience the world from another person's perspective, would we become more empathetic?",
            "Why do we often find ourselves lost in thought?",
            "What if our dreams are actually glimpses into our own future?",
            "If we could control gravity, how would it change our lives?",
            "Why do we find it so difficult to change our habits?",
            "What if we could see the consequences of our choices before we make them?",
            "If we could create a perfect utopia, what would it look like?",
            "Why do we find patterns in random events?",
            "What if we could create a machine that could predict the future with 100% accuracy?",
            "If we could communicate with the dead, what would we learn?",
            "Why do we feel so small in the face of the universe?",
            "What if we could tap into the full potential of our brains?",
            "If we could create a device that could cure any disease, what impact would it have on society?",
            "Why do we tend to remember negative events more vividly than positive ones?",
            "What if we could communicate with other intelligent life forms in the universe?",
            "If we could create a machine that could generate infinite energy, what would we do with it?",
            "Why do we often underestimate the power of small actions?",
            "What if we could communicate with the future?",
            "If we could create a machine that could unlock the secrets of the universe, what would we discover?",
            "Why do we find comfort in routine?",
            "What if we could create a machine that could resurrect the dead?",
            "If we could create a machine that could generate infinite resources, how would it change our society?",
            "Why do we have a sense of morality?",
            "What if we could create a machine that could create new universes?",
            "If we could communicate with the universe as a whole, what would it tell us?",
            "Why do we find beauty in art?",
            "What if we could create a machine that could control time?",
            "If we could create a machine that could generate infinite knowledge, what would we do with it?",
            "Why do we feel the need to explore?",
            "What if we could create a machine that could create life?",
            "If we could create a machine that could understand the meaning of life, what would it tell us?",
            "I'd always thought lightning was something only I could see.",
            "A dead duck doesn't fly backward.",
            "He kept telling himself that one day it would all somehow make sense.",
            "The anaconda was the greatest criminal mastermind in this part of the neighborhood.",
            "He found his art never progressed when he literally used his sweat and tears.",
            "You can't compare apples and oranges, but what about bananas and plantains?",
            "He was an introvert that extroverts seemed to love.",
            "Warm beer on a cold day isn't my idea of fun.",
            "Some bathing suits just shouldn't be worn by some people.",
            "I think I will buy the red car, or I will lease the blue one.",
            "He embraced his new life as an eggplant.",
            "It isn't difficult to do a handstand if you just stand on your hands.",
            "He ended up burning his fingers poking someone else's fire.",
            "He excelled at firing people nicely.",
            "My Mum tries to be cool by saying that she likes all the same things that I do.",
            "They say that dogs are man's best friend, but this cat was setting out to sabotage that theory.",
            "When he had to picnic on the beach, he purposely put sand in other people's food.",
            "Homesickness became contagious in the young campers' cabin.",
            "Swim at your own risk was taken as a challenge for the group of Kansas City college students.",
            "The lake is a long way from here.",
            "The waitress was not amused when he ordered green eggs and ham.",
            "It took him a while to realize that everything he decided not to change, he was actually choosing.",
            "He liked to play with words in the bathtub.",
            "Choosing to do nothing is still a choice, after all.",
            "The thunderous roar of the jet overhead confirmed her worst fears.",
            "He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility.",
            "It was getting dark, and we weren't there yet.",
            "There's a message for you if you look up.",
            "Of course, she loves her pink bunny slippers.",
            "He dreamed of leaving his law firm to open a portable dog wash.",
            "The tumbleweed refused to tumble but was more than willing to prance.",
            "Today I heard something new and unmemorable.",
            "Hang on, my kittens are scratching at the bathtub and they'll upset by the lack of biscuits.",
            "She saw no irony asking me to change but wanting me to accept her for who she is.",
            "The tears of a clown make my lipstick run, but my shower cap is still intact.",
            "We're careful about orange ping pong balls because people might think they're fruit.",
            "She borrowed the book from him many years ago and hasn't yet returned it.",
            "Tomorrow will bring something new, so leave today as a memory.",
            "Bill ran from the giraffe toward the dolphin.",
            "Douglas figured the best way to succeed was to do the opposite of what he'd been doing all his life.",
            "He barked orders at his daughters but they just stared back with amusement.",
            "Gwen had her best sleep ever on her new bed of nails.",
            "Whenever he saw a red flag warning at the beach he grabbed his surfboard.",
            "The family's excitement over going to Disneyland was crazier than she anticipated.",
            "His ultimate dream fantasy consisted of being content and sleeping eight hours in a row.",
            "Nudist colonies shun fig-leaf couture.",
            "The father died during childbirth.",
            "In hopes of finding out the truth, he entered the one-room library.",
            "He had a wall full of masks so she could wear a different face every day.",
            "He told us a very exciting adventure story.",
            "The wake behind the boat told of the past while the open sea for told life in the unknown future.",
            "Truth in advertising and dinosaurs with skateboards have much in common.",
            "The fish listened intently to what the frogs had to say.",
            "I'd always thought lightning was something only I could see.",
            "Please wait outside of the house.",
            "Green should have smelled more tranquil, but somehow it just tasted rotten.",
            "The virus had powers none of us knew existed.",
            "Red is greener than purple, for sure.",
            "The stench from the feedlot permeated the car despite having the air conditioning on recycled air.",
            "I was starting to worry that my pet turtle could tell what I was thinking.",
            "My biggest joy is roasting almonds while stalking prey.",
            "He colored deep space a soft yellow.",
            "Just because the water is red doesn't mean you can't drink it.",
            "He drank life before spitting it out.",
            "The worst thing about being at the top of the career ladder is that there's a long way to fall.",
            "The random sentence generator generated a random sentence about a random sentence.",
            "The efficiency we have at removing trash has made creating trash more acceptable.",
            "I caught my squirrel rustling through my gym bag.",
            "They're playing the piano while flying in the plane.",
            "She was the type of girl that always burnt sugar to show she cared.",
            "She was amazed by the large chunks of ice washing up on the beach.",
            "Behind the window was a reflection that only instilled fear.",
            "She had convinced her kids that any mushroom found on the ground would kill them if they touched it.",
            "You bite up because of your lower jaw.",
            "Lightning Paradise was the local hangout joint where the group usually ended up spending the night.",
            "The lyrics of the song sounded like fingernails on a chalkboard.",
            "He watched the dancing piglets with panda bear tummies in the swimming pool.",
            "The truth is that you pay for your lifestyle in hours.",
            "He looked behind the door and didn't like what he saw.",
            "Plans for this weekend include turning wine into water.",
            "They throw cabbage that turns your brain into emotional baggage.",
            "The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle's disappearance.",
            "The quick brown fox jumps over the lazy dog.",
            "The door slammed on the watermelon.",
            "She wanted to be rescued, but only if it was Tuesday and raining.",
            "Today arrived with a crash of my car through the garage door.",
            "Normal activities took extraordinary amounts of concentration at the high altitude.",
            "Rock music approaches at high velocity.",
            "She wanted a pet platypus but ended up getting a duck and a ferret instead.",
            "The knives were out and she was sharpening hers.",
            "Too many prisons have become early coffins.",
            "The crowd yells and screams for more memes.",
            "The fifty mannequin heads floating in the pool kind of freaked them out.",
            "Be careful with that butter knife.",
            "Three generations with six decades of life experience.",
            "If eating three-egg omelets causes weight-gain, budgie eggs are a good substitute.",
            "The group quickly understood that toxic waste was the most effective barrier to use against the zombies.",
            "She opened up her third bottle of wine of the night.",
            "Karen realized the only way she was getting into heaven was to cheat.",
            "It was difficult for Mary to admit that most of her workout consisted of exercising poor judgment.",
            "It's much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball.",
            "If my calculator had a history, it would be more embarrassing than my browser history.",
            "She couldn't understand why nobody else could see that the sky is full of cotton candy.",
            "Peanut butter and jelly caused the elderly lady to think about her past.",
            "He played the game as if his life depended on it and the truth was that it did.",
            "A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.",
            "Lucifer was surprised at the amount of life at Death Valley.",
            "She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
            "Flying fish flew by the space station.",
            "The child's favorite Christmas gift was the large box her father's lawnmower came in.",
            "It's always a good idea to seek shelter from the evil gaze of the sun.",
            "She tilted her head back and let whip cream stream into her mouth while taking a bath.",
            "The changing of down comforters to cotton bedspreads always meant the squirrels had returned.",
            "He wondered why at 18 he was old enough to go to war, but not old enough to buy cigarettes.",
            "He was sure the Devil created red sparkly glitter.",
            "I ate a sock because people on the Internet told me to.",
            "He spiked his hair green to support his iguana.",
            "Abstraction is often one floor above you.",
            "Edith could decide if she should paint her teeth or brush her nails.",
            "When I cook spaghetti, I like to boil it a few minutes past al dente so the noodles are super slippery.",
            "The water flowing down the river didn't look that powerful from the car",
            "The manager of the fruit stand always sat and only sold vegetables.",
            "The body piercing didn't go exactly as he expected.",
            "Purple is the best city in the forest.",
            "The miniature pet elephant became the envy of the neighborhood.",
            "If I don't like something, I'll stay away from it.",
            "I am my aunt's sister's daughter.",
            "He realized there had been several deaths on this road, but his concern rose when he saw the exact number.",
            "They say people remember important moments in their life well, yet no one even remembers their own birth.",
            "Most shark attacks occur about 10 feet from the beach since that's where the people are.",
            "She discovered van life is difficult with 2 cats and a dog.",
            "The blue parrot drove by the hitchhiking mongoose.",
            "I am happy to take your donation; any amount will be greatly appreciated.",
            "The overpass went under the highway and into a secret world.",
            "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with Grandpa Joe in the hospital.",
            "Two seats were vacant.",
            "There can never be too many cherries on an ice cream sundae.",
            "As time wore on, simple dog commands turned into full paragraphs explaining why the dog couldn't do something.",
            "The bird had a belief that it was really a groundhog.",
            "Today I bought a raincoat and wore it on a sunny day.",
            "The skeleton had skeletons of his own in the closet.",
            "The tree fell unexpectedly short.",
            "He decided that the time had come to be stronger than any of the excuses he'd used until then.",
            "I'm confused: when people ask me what's up, and I point, they groan.",
            "The busker hoped that the people passing by would throw money, but they threw tomatoes instead, so he exchanged his hat for a juicer.",
            "The old rusted farm equipment surrounded the house predicting its demise.",
            "He had unknowingly taken up sleepwalking as a nighttime hobby.",
            "She was only made the society president because she can whistle with her toes.",
            "The toy brought back fond memories of being lost in the rain forest.",
            "The beauty of the sunset was obscured by the industrial cranes.",
            "She wasn't sure whether to be impressed or concerned that he folded underwear in neat little packages.",
            "Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.",
            "It doesn't sound like that will ever be on my travel list.",
            "She did a happy dance because all of the socks from the dryer matched.",
            "I liked their first two albums but changed my mind after that charity gig.",
            "The rusty nail stood erect, angled at a 45-degree angle, just waiting for the perfect barefoot to come along.",
            "People keep telling me \"orange\" but I still prefer \"pink\".",
            "Charles ate the french fries knowing they would be his last meal.",
            "It took me too long to realize that the ceiling hadn't been painted to look like the sky.",
            "Instead of a bachelorette party",
            "The river stole the gods.",
            "My secretary is the only person who truly understands my stamp-collecting obsession.",
            "He figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
            "He didn't heed the warning and it had turned out surprisingly well.",
            "There is no better feeling than staring at a wall with closed eyes.",
            "It must be five o'clock somewhere.",
            "Sometimes it is better to just walk away from things and go back to them later when you're in a better frame of mind.",
            "They were excited to see their first sloth.",
            "Peter found road kill an excellent way to save money on dinner.",
            "The paintbrush was angry at the color the artist chose to use.",
            "Shingle color was not something the couple had ever talked about.",
            "There was no ice cream in the freezer, nor did they have money to go to the store.",
            "To the surprise of everyone, the Rapture happened yesterday but it didn't quite go as expected.",
            "The delicious aroma from the kitchen was ruined by cigarette smoke.",
            "I often see the time 11:11 or 12:34 on clocks.",
            "She found his complete dullness interesting.",
            "The sight of his goatee made me want to run and hide under my sister-in-law's bed.",
            "Three years later, the coffin was still full of Jello.",
            "Waffles are always better without fire ants and fleas.",
            "She did not cheat on the test, for it was not the right thing to do.",
            "Everybody should read Chaucer to improve their everyday vocabulary.",
            "He decided to count all the sand on the beach as a hobby.",
            "He wondered if she would appreciate his toenail collection.",
            "Tom got a small piece of pie.",
            "She had some amazing news to share but nobody to share it with.",
            "I would be delighted if the sea were full of cucumber juice.",
            "his seven-layer cake only had six layers.",
            "Nancy decided to make the porta-potty her home.",
            "It was obvious she was hot, sweaty, and tired.",
            "He strives to keep the best lawn in the neighborhood.",
            "I never knew what hardship looked like until it started raining bowling balls.",
            "She hadn't had her cup of coffee, and that made things all the worse.",
            "Martha came to the conclusion that shake weights are a great gift for any occasion."
        ]
    } 
}